//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeFieldValues2Entity
    {
        public long Id { get; set; }
        public long MemberSetFactId { get; set; }
        public int FreeFieldId { get; set; }
        public int FFValueTypeId { get; set; }
        public string Value { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> MemberFreeFieldId { get; set; }
    
        public virtual FreeFieldEntity FreeField { get; set; }
        public virtual MemberSetFactEntity MemberSetFact { get; set; }
    }
}
