//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeFieldEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FreeFieldEntity()
        {
            this.FreeFieldValues = new HashSet<FreeFieldValueEntity>();
            this.MemberListFreeFields = new HashSet<MemberListFreeFieldEntity>();
            this.RuleFreeFields = new HashSet<RuleFreeFieldEntity>();
            this.FreeFieldValues2 = new HashSet<FreeFieldValues2Entity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Datatype { get; set; }
        public Nullable<int> CheckMemberListId { get; set; }
        public string Description { get; set; }
        public byte CheckTypeId { get; set; }
        public string CheckExpr { get; set; }
    
        public virtual MemberListEntity MemberList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreeFieldValueEntity> FreeFieldValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberListFreeFieldEntity> MemberListFreeFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleFreeFieldEntity> RuleFreeFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreeFieldValues2Entity> FreeFieldValues2 { get; set; }
    }
}
