//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicatorHierarchyEntity
    {
        public int ParentIndicatorId { get; set; }
        public int SourceIndicatorId { get; set; }
        public int Operator { get; set; }
        public double SortOrder { get; set; }
        public int Id { get; set; }
    
        public virtual IndicatorEntity ParentIndicator { get; set; }
        public virtual IndicatorEntity SourceIndicator { get; set; }
    }
}
