//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicatorFormulaEntity
    {
        public int IndicatorId { get; set; }
        public string FormulaSQL { get; set; }
        public string FormulaMDX { get; set; }
        public string FormulaXLS { get; set; }
    
        public virtual IndicatorEntity Indicator { get; set; }
    }
}
