//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicatorEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndicatorEntity()
        {
            this.CalculationsAsParent = new HashSet<IndicatorCalculationEntity>();
            this.CalculationsAsSource = new HashSet<IndicatorCalculationEntity>();
            this.HierarchiesAsParent = new HashSet<IndicatorHierarchyEntity>();
            this.HierarchiesAsSource = new HashSet<IndicatorHierarchyEntity>();
            this.ReportRows = new HashSet<ReportRowEntity>();
            this.ConstantValues = new HashSet<ConstantValueEntity>();
            this.ModelIndicators = new HashSet<ModelIndicatorEntity>();
            this.TagRelations = new HashSet<TagRelationEntity>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public double SortOrder { get; set; }
        public byte AggregationTypeId { get; set; }
        public bool Imported { get; set; }
        public int UnitOfMeasureId { get; set; }
        public byte NumPrecision { get; set; }
        public int DivideBy { get; set; }
        public string Description { get; set; }
        public bool Blocked { get; set; }
    
        public virtual AggregationTypeEntity AggregationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorCalculationEntity> CalculationsAsParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorCalculationEntity> CalculationsAsSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorHierarchyEntity> HierarchiesAsParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorHierarchyEntity> HierarchiesAsSource { get; set; }
        public virtual IndicatorTypeEntity IndicatorType { get; set; }
        public virtual UnitEntity Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportRowEntity> ReportRows { get; set; }
        public virtual IndicatorFormulaEntity IndicatorFormula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstantValueEntity> ConstantValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelIndicatorEntity> ModelIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagRelationEntity> TagRelations { get; set; }
    }
}
