//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLabelEntity
    {
        public int Id { get; set; }
        public int MemberListId { get; set; }
        public string Name { get; set; }
        public string FieldName { get; set; }
        public bool Visible { get; set; }
    
        public virtual MemberListEntity MemberList { get; set; }
    }
}
