//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberSetFactEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberSetFactEntity()
        {
            this.FreeFieldValues2 = new HashSet<FreeFieldValues2Entity>();
        }
    
        public long Id { get; set; }
        public int ModelId { get; set; }
        public long MemberSetId { get; set; }
        public Nullable<int> TimeId { get; set; }
        public Nullable<int> IndicatorId { get; set; }
        public Nullable<int> PlanId { get; set; }
        public Nullable<int> DimRuleId { get; set; }
        public Nullable<int> TimeRuleId { get; set; }
        public Nullable<int> IndRuleId { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<long> DimRuleParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreeFieldValues2Entity> FreeFieldValues2 { get; set; }
        public virtual MemberSetEntity MemberSet { get; set; }
        public virtual RuleEntity Rule { get; set; }
        public virtual RuleEntity Rule1 { get; set; }
        public virtual RuleEntity Rule2 { get; set; }
        public virtual ModelEntity Model { get; set; }
    }
}
