//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberListFreeFieldEntity
    {
        public int Id { get; set; }
        public int MemberListId { get; set; }
        public int FreeFieldId { get; set; }
        public bool Imported { get; set; }
    
        public virtual FreeFieldEntity FreeField { get; set; }
        public virtual MemberListEntity MemberList { get; set; }
    }
}
