//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelSharingDimensionalityEntity
    {
        public int Id { get; set; }
        public int SharingId { get; set; }
        public int ModelIndicatorId { get; set; }
        public int DimHierarchyLevelId { get; set; }
    
        public virtual HierarchyLevelEntity HierarchyLevel { get; set; }
        public virtual ModelIndicatorEntity ModelIndicator { get; set; }
        public virtual ModelValuesSharingEntity ModelValuesSharing { get; set; }
    }
}
