//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelIndicatorValueSourceEntity
    {
        public int Id { get; set; }
        public int ModelIndicatorId { get; set; }
        public int PlanId { get; set; }
        public int TimeDetailLevelId { get; set; }
        public byte TimeInputTypeId { get; set; }
        public int DimDetailLevelId { get; set; }
        public string SourceName { get; set; }
        public string Description { get; set; }
    
        public virtual IndicatorValueTypeEntity IndicatorValueType { get; set; }
    }
}
