//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelReportEntity
    {
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int ReportId { get; set; }
        public int DimHierarchyId { get; set; }
        public int DimDetailLevel { get; set; }
        public int TimeHierarchyId { get; set; }
        public int TimeDetailLevel { get; set; }
    
        public virtual ReportEntity Report { get; set; }
        public virtual ModelEntity Model { get; set; }
    }
}
