//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDefinitionEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TreePath { get; set; }
        public string Description { get; set; }
        public string Documentation { get; set; }
        public byte[] Image { get; set; }
        public int Version { get; set; }
        public System.Guid DefinitionObjectUId { get; set; }
        public System.Guid DefinitionUId { get; set; }
        public string ShapeColor { get; set; }
        public Nullable<int> ShapeType { get; set; }
        public bool HasCustomParameters { get; set; }
        public int UserId { get; set; }
    }
}
