//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NInputDefinitionEntity
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> InputType { get; set; }
        public string Expression { get; set; }
        public Nullable<int> InputSettingsId { get; set; }
        public bool IsAdvancedParameter { get; set; }
        public int DefinitionId { get; set; }
        public string AliasName { get; set; }
        public int Order { get; set; }
        public bool IsVisible { get; set; }
        public string ParameterName { get; set; }
        public string Group { get; set; }
        public string AmbicaBIParameterDefaultValue { get; set; }
    }
}
