//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NParameterMappingEntity
    {
        public int Id { get; set; }
        public System.Guid ParameterFromUId { get; set; }
        public System.Guid ParameterToUId { get; set; }
        public System.Guid WorkflowUId { get; set; }
        public System.Guid ConnectorUId { get; set; }
        public bool IsDefinition { get; set; }
    }
}
