//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NWorkflowEntity
    {
        public int Id { get; set; }
        public System.Guid UId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Xml { get; set; }
        public bool IsDefinition { get; set; }
        public Nullable<int> DefinitionId { get; set; }
    }
}
