//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterEntity
    {
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
        public int Editable { get; set; }
        public string Description { get; set; }
        public string Group { get; set; }
        public string Name { get; set; }
        public string SubCategory { get; set; }
        public string ValueDataType { get; set; }
        public byte Type { get; set; }
        public string RegEx { get; set; }
    }
}
