//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRelationEntity
    {
        public int Id { get; set; }
        public int ParentPermissionTypeId { get; set; }
        public int ChildPermissionTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual PermissionTypeEntity PermissionType { get; set; }
        public virtual PermissionTypeEntity PermissionType1 { get; set; }
    }
}
