//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionEntity()
        {
            this.PermissionRoles = new HashSet<PermissionRoleEntity>();
        }
    
        public int Id { get; set; }
        public int PermissionTypeId { get; set; }
        public int ObjectTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ObjectTypeEntity ObjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionRoleEntity> PermissionRoles { get; set; }
        public virtual PermissionTypeEntity PermissionType { get; set; }
    }
}
