//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportRelationEntity
    {
        public int ParentReportId { get; set; }
        public int ChildReportId { get; set; }
        public int Id { get; set; }
        public double SortOrder { get; set; }
    
        public virtual ReportEntity ChildReport { get; set; }
        public virtual ReportEntity ParentReport { get; set; }
    }
}
