//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportEntity()
        {
            this.ReportRows = new HashSet<ReportRowEntity>();
            this.RelationsAsChild = new HashSet<ReportRelationEntity>();
            this.RelationsAsParent = new HashSet<ReportRelationEntity>();
            this.ModelReports = new HashSet<ModelReportEntity>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public double SortOrder { get; set; }
        public byte ModuleType { get; set; }
        public Nullable<byte> CalculationType { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<byte> PerspectiveType { get; set; }
        public Nullable<int> OutputId { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> ObjectiveType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportRowEntity> ReportRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportRelationEntity> RelationsAsChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportRelationEntity> RelationsAsParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelReportEntity> ModelReports { get; set; }
        public virtual ObjectiveTypeEntity ObjectiveType1 { get; set; }
    }
}
