//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleEntity()
        {
            this.RuleFreeFields = new HashSet<RuleFreeFieldEntity>();
            this.RuleDimRows = new HashSet<RuleDimRowEntity>();
            this.MemberSetFacts = new HashSet<MemberSetFactEntity>();
            this.MemberSetFacts1 = new HashSet<MemberSetFactEntity>();
            this.MemberSetFacts2 = new HashSet<MemberSetFactEntity>();
            this.RuleTimeRows = new HashSet<RuleTimeRowEntity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RuleTypeId { get; set; }
        public Nullable<int> MemberListId { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleFreeFieldEntity> RuleFreeFields { get; set; }
        public virtual RuleTypeEntity RuleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleDimRowEntity> RuleDimRows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSetFactEntity> MemberSetFacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSetFactEntity> MemberSetFacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSetFactEntity> MemberSetFacts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleTimeRowEntity> RuleTimeRows { get; set; }
    }
}
