//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleEntity()
        {
            this.WorkflowSchedules = new HashSet<WorkflowScheduleEntity>();
        }
    
        public int Id { get; set; }
        public int ScheduleType { get; set; }
        public int FrequencyType { get; set; }
        public int FrequencyInterval { get; set; }
        public string FreqSubInterval { get; set; }
        public int TimeFrequencyType { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedUserId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TimeFrequencyInterval { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowScheduleEntity> WorkflowSchedules { get; set; }
    }
}
