//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerLogEntity
    {
        public long Id { get; set; }
        public int SenderId { get; set; }
        public int MessageType { get; set; }
        public string Text { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
