//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepParametersValueEntity
    {
        public int StepId { get; set; }
        public string ParameterCode { get; set; }
        public string Value { get; set; }
        public Nullable<int> Order { get; set; }
        public long Id { get; set; }
    
        public virtual WorkflowStepEntity WorkflowStep { get; set; }
    }
}
