//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeMemberListEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeMemberListEntity()
        {
            this.TimeMemberListRelationsAsChild = new HashSet<TimeMemberListRelationEntity>();
            this.TimeMemberListRelationsAsParent = new HashSet<TimeMemberListRelationEntity>();
            this.TimeHierarchyLevels = new HashSet<TimeHierarchyLevelEntity>();
            this.TimeMembers = new HashSet<TimeMemberEntity>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> SourceMemberListId { get; set; }
        public string ImportColumnName { get; set; }
        public string OlapAttributeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeMemberListRelationEntity> TimeMemberListRelationsAsChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeMemberListRelationEntity> TimeMemberListRelationsAsParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeHierarchyLevelEntity> TimeHierarchyLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeMemberEntity> TimeMembers { get; set; }
    }
}
