//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeMemberRelationEntity
    {
        public int MemberListRelationId { get; set; }
        public int ParentMemberId { get; set; }
        public int ChildMemberId { get; set; }
    
        public virtual TimeMemberListRelationEntity TimeMemberListRelation { get; set; }
        public virtual TimeMemberEntity ChildTimeMember { get; set; }
        public virtual TimeMemberEntity ParentTimeMember { get; set; }
    }
}
