//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeHierarchyLevelEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeHierarchyLevelEntity()
        {
            this.ModelIndicatorDetailLevels = new HashSet<ModelIndicatorDetailLevelEntity>();
            this.ModelIndicatorValueSources = new HashSet<ModelIndicatorValueSourceEntity>();
            this.ModelIndicatorValueSourceTimeLevels = new HashSet<ModelIndicatorValueSourceTimeLevelEntity>();
            this.ModelValueSourceTimeLevels = new HashSet<ModelValueSourceTimeLevelEntity>();
            this.ModelDimensionalities = new HashSet<ModelDimensionalityEntity>();
            this.ModelValueSources = new HashSet<ModelValueSourceEntity>();
        }
    
        public int Id { get; set; }
        public int HierarchyId { get; set; }
        public int LevelOrdinal { get; set; }
        public string Name { get; set; }
        public int MemberListId { get; set; }
        public Nullable<int> UpMemberListRelationId { get; set; }
        public Nullable<int> DownMemberListRelationId { get; set; }
    
        public virtual TimeHierarchyEntity TimeHierarchy { get; set; }
        public virtual TimeMemberListEntity TimeMemberList { get; set; }
        public virtual TimeMemberListRelationEntity ChildTimeMemberListRelation { get; set; }
        public virtual TimeMemberListRelationEntity ParentTimeMemberListRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelIndicatorDetailLevelEntity> ModelIndicatorDetailLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelIndicatorValueSourceEntity> ModelIndicatorValueSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelIndicatorValueSourceTimeLevelEntity> ModelIndicatorValueSourceTimeLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelValueSourceTimeLevelEntity> ModelValueSourceTimeLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelDimensionalityEntity> ModelDimensionalities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelValueSourceEntity> ModelValueSources { get; set; }
    }
}
