//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeMemberEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeMemberEntity()
        {
            this.TimeMemberRelationsAsChild = new HashSet<TimeMemberRelationEntity>();
            this.TimeMemberRelationsAsParent = new HashSet<TimeMemberRelationEntity>();
            this.ValueTypes = new HashSet<ValueTypeEntity>();
            this.Meetings = new HashSet<MeetingEntity>();
        }
    
        public int Id { get; set; }
        public int MemberListId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<int> FirstDayId { get; set; }
        public Nullable<int> LastDayId { get; set; }
        public Nullable<bool> WorkDayFlag { get; set; }
        public Nullable<int> SourceMemberId { get; set; }
    
        public virtual TimeMemberListEntity TimeMemberList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeMemberRelationEntity> TimeMemberRelationsAsChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeMemberRelationEntity> TimeMemberRelationsAsParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValueTypeEntity> ValueTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingEntity> Meetings { get; set; }
    }
}
