//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStepDetailEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowStepDetailEntity()
        {
            this.WorkflowStepDimFilters = new HashSet<WorkflowStepDimFilterEntity>();
            this.WorkflowStepIndicators = new HashSet<WorkflowStepIndicatorEntity>();
            this.WorkflowStepTimeFilters = new HashSet<WorkflowStepTimeFilterEntity>();
        }
    
        public int Id { get; set; }
        public int WorkflowStepId { get; set; }
        public int WorkflowStepDetailTypeId { get; set; }
        public byte OrderNo { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> ValueTypeId { get; set; }
        public Nullable<int> SubIndicatorId { get; set; }
        public Nullable<bool> Recalculate { get; set; }
        public Nullable<decimal> InsertedValue { get; set; }
        public Nullable<decimal> DissolvePercent { get; set; }
        public Nullable<bool> DissolveBySourceYear { get; set; }
        public Nullable<int> PlacementTypeId { get; set; }
        public Nullable<int> RoundRank { get; set; }
        public Nullable<bool> Reset { get; set; }
        public Nullable<int> DimFilterType { get; set; }
        public Nullable<int> DimDetailLevel { get; set; }
        public Nullable<int> TimeFilterType { get; set; }
        public Nullable<int> TimeDetailLevel { get; set; }
        public Nullable<int> DimHierarchyId { get; set; }
        public Nullable<int> TimeHierarchyId { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<int> DimAggType { get; set; }
        public Nullable<int> TimeAggType { get; set; }
        public Nullable<int> IndDetailLevel { get; set; }
        public Nullable<int> IndAggLevel { get; set; }
        public Nullable<int> ResultRoundType { get; set; }
    
        public virtual PlacementTypeEntity PlacementType { get; set; }
        public virtual WorkflowStepDetailTypeEntity WorkflowStepDetailType { get; set; }
        public virtual WorkflowStepEntity WorkflowStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowStepDimFilterEntity> WorkflowStepDimFilters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowStepIndicatorEntity> WorkflowStepIndicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowStepTimeFilterEntity> WorkflowStepTimeFilters { get; set; }
        public virtual ModelEntity Model { get; set; }
    }
}
