//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTestApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStepDimFilterEntity
    {
        public int Id { get; set; }
        public int WorkflowStepDetailId { get; set; }
        public int HierarchyLevel { get; set; }
        public long MemberId { get; set; }
    
        public virtual WorkflowStepDetailEntity WorkflowStepDetail { get; set; }
    }
}
